baseurl:    "http://blog.yudppp.com"
title:      "◯ △ □"
contentdir: "content"
layoutdir:  "layouts"
staticdir:  "static"
uglyUrls:   false
metaDataFormat: "yaml"
params:
  description:  "techblog - yudppp"
permalinks:
  post: /:year/:title/ 